apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sdp-hps
  labels:
    app: sdp-hps
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  scaleTargetRef:
    kind: Deployment
    name: sensor-data-processing-service
