spring.application.name=sensor-data-processing-service
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USERNAME:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}
spring.rabbitmq.virtual-host=/

spring.datasource.url=jdbc:mariadb://localhost:3306/sensor-platform
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=7676

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false