namespace: sensor-platform

resources:
  - definition.yaml
  - credentials/credentials-rabbitqm.yaml
  - credentials/credentials-db.yaml
  - sensor-data-ingestion-service/sensor-data-ingestion.yaml
  - sensor-data-processing-service/sensor-data-processing.yaml
  - sensor-management-service/sensor-management.yaml
  - sensor-query-service/sensor-query.yaml
  - db/maria-db.yaml
  - networking/gateway.yaml
