apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-management-service
  labels:
    app: sensor-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-management-service
  template:
    metadata:
      name: sensor-management-service
      labels:
        app: sensor-management-service
    spec:
      containers:
        - name: sensor-management-service
          image: ghcr.io/selfiekonrad/sensor-management-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: db_url
                  name: credentials-db
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: db_username
                  name: credentials-db
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: db_password
                  name: credentials-db
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-management-service
  labels:
    app: sensor-management-service
spec:
  type: ClusterIP
  selector:
    app: sensor-management-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
