apiVersion: v1
kind: ConfigMap
metadata:
  name: credentials-rabbitqm
data:
  rabbit_host: "my-rabbit.sensor-platform.svc.cluster.local"
  rabbit_port: "5672"
  rabbit_username: "ZGVmYXVsdF91c2VyX2w3SERzY0d2OThrQVR6cnNfS2g="
  rabbit_password: "YlUwM3hkYnBESTZYeDNtaGdPeHk1aDQ5NkVfczVldEU="
