apiVersion: v1
kind: ConfigMap
metadata:
  name: credentials-rabbitqm
data:
  rabbit_host: "my-rabbit.sensor-platform.svc.cluster.local"
  rabbit_port: "5672"
  rabbit_username: "default_user_CIg1bpp02TQs5wGsuwR"
  rabbit_password: "EJxuLW0sF6LjNByxLQVqQOYsgYb_i3kF"
