apiVersion: v1
kind: ConfigMap
metadata:
  name: credentials-rabbitqm
data:
  rabbit_host: "my-rabbit.sensor-platform.svc.cluster.local"
  rabbit_port: "5672"
  rabbit_username: "default_user_l7HDscGv98kATzrs_Kh"
  rabbit_password: "bU03xdbpDI6Xx3mhgOxy5h496E_s5etE"
